# Generated by Django 3.2.7 on 2021-09-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
